### ISSUE TITLE
Library should slice manage_merchant from access token

### ISSUE THREAD

**Issue by almonk** [gocardless/gocardless-legacy-ruby#62]
As a partner, if you oauth a new merchant you get an access token that looks something like:

```
9FQH4H....2Y4DHCF manage_merchant:0215THTTY
```

If you pass this token back when you init a new GoCardless client, you get the following warning:

```
[DEPRECATION] (gocardless-ruby) merchant_id is now a separate attribute, the manage_merchant scope should no longer be included in the 'token' attribute. See http://git.io/G9y37Q for more info.
```

IMO we should either remove the manage_merchant from the access token, or build the slicing of the superfluous string into the Ruby client.

Thoughts?

**Comment by dbourguignon** [comment]
Hi all,

As far as I know, I still have the deprecation warning though using a version including this patch.
It's not clear what changes I should make to my code as a merchant to fix that.
Should I remove the manage_merchant:… bits from my stored access_token?
